rate: 10
node_name: "move_to_pose"

target_cart_pose:
  position:
    x: 0.5
    y: 0.5
    z: 0.5
  orientation:
    x: 0
    y: 0
    z: 0
    w: 1

inverse_kinematics:
  type: "relaxed-IK"
  service: "relaxed_ik/solve_pose"
  topic: "relaxed_ik/ee_pose_goals"
  use_service: True


# hard coding joint values for the panda arm
hardcoding:
  use_hardcoding: True
  hardcoding_joint_pose:
    $(arg arm_id)_joint1: 0
    $(arg arm_id)_joint2: -0.785398163397
    $(arg arm_id)_joint3: 0
    $(arg arm_id)_joint4: -2.35619449019
    $(arg arm_id)_joint5: 0
    $(arg arm_id)_joint6: 1.57079632679
    $(arg arm_id)_joint7: 0.785398163397
  hardcoding_gripper_config:
    width: 0.05
    speed: 0.05

debugger:
  evaluate_time: True